import {
  Brain,
  Layers,
  Layers2,
  Sliders,
  Hash,
  Frame,
  Sparkles,
  Ghost,
  Settings,
  Thermometer,
  Copy,
  GitBranch,
  Network,
  Bot,
  Repeat,
  ListChecks,
  Search,
  Users,
  Workflow,
  Database,
  Compass,
  DatabaseZap,
  Scissors,
  Clock,
  Archive,
  Wrench,
  Plug,
  Cable,
  Terminal,
  Mountain,
  GraduationCap,
  ThumbsUp,
  Cog,
  Minimize2,
  Cpu,
  Link as LinkIcon,
  GitFork,
  LayoutGrid,
  Server,
  Globe,
  ServerCog,
  Circle,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  brain: Brain,
  layers: Layers,
  layers2: Layers2,
  sliders: Sliders,
  hash: Hash,
  frame: Frame,
  sparkles: Sparkles,
  ghost: Ghost,
  settings: Settings,
  thermometer: Thermometer,
  copy: Copy,
  "git-branch": GitBranch,
  network: Network,
  bot: Bot,
  repeat: Repeat,
  "list-checks": ListChecks,
  search: Search,
  users: Users,
  workflow: Workflow,
  database: Database,
  compass: Compass,
  "database-zap": DatabaseZap,
  scissors: Scissors,
  clock: Clock,
  archive: Archive,
  wrench: Wrench,
  plug: Plug,
  cable: Cable,
  terminal: Terminal,
  mountain: Mountain,
  "graduation-cap": GraduationCap,
  "thumbs-up": ThumbsUp,
  cog: Cog,
  "minimize-2": Minimize2,
  cpu: Cpu,
  link: LinkIcon,
  "git-fork": GitFork,
  "layout-grid": LayoutGrid,
  server: Server,
  globe: Globe,
  "server-cog": ServerCog,
  circle: Circle,
};

export function Icon({
  name,
  className,
  strokeWidth = 1.5,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const C = ICON_MAP[name] ?? Circle;
  return <C className={className} strokeWidth={strokeWidth} />;
}
